title: github pages
author: sajasmohammed
email: sajasam97@gmail.com
description: sdfghsdfghdfg
baseurl: sdfgh
theme: minima


# social links
twitter_username: sajasmohammed
github_username:  sajasmohammed

show_excerpts: false
