title: github pages
author: sajasmohammed
email: sajasam97@gmail.com
description: sdfghsdfghdfg
baseurl: sdfgh

# social links
twitter_username: sajasmohammed # DO NOT include the @ character, or else the build will fail!
github_username:  sajasmohammed # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
